# Generated by Django 4.2.3 on 2023-07-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(upload_to='actors/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(upload_to='poster/', verbose_name='Постер'),
        ),
    ]
